---
dependencies:
  - role: kubernetes-apps/ansible
    when:
      - inventory_hostname == groups['kube_control_plane'][0]

  - role: kubernetes-apps/helm_operator
    when:
      - helm_operator_enabled
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - helm_operator

  - role: kubernetes-apps/krew
    when:
      - krew_enabled
    tags:
      - krew

  - role: kubernetes-apps/registry
    when:
      - registry_enabled
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - registry

  - role: kubernetes-apps/metrics_server
    when:
      - metrics_server_enabled
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - metrics_server

  - role: kubernetes-apps/csi_driver/csi_crd
    when:
      - cinder_csi_enabled
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - csi-driver

  - role: kubernetes-apps/csi_driver/cinder
    when:
      - cinder_csi_enabled
    tags:
      - cinder-csi-driver
      - csi-driver

  - role: kubernetes-apps/csi_driver/aws_ebs
    when:
      - aws_ebs_csi_enabled
    tags:
      - aws-ebs-csi-driver
      - csi-driver

  - role: kubernetes-apps/csi_driver/azuredisk
    when:
      - azure_csi_enabled
    tags:
      - azure-csi-driver
      - csi-driver

  - role: kubernetes-apps/csi_driver/gcp_pd
    when:
      - gcp_pd_csi_enabled
    tags:
      - gcp-pd-csi-driver
      - csi-driver

  - role: kubernetes-apps/csi_driver/vsphere
    when:
      - vsphere_csi_enabled
    tags:
      - vsphere-csi-driver
      - csi-driver

  - role: kubernetes-apps/persistent_volumes
    when:
      - persistent_volumes_enabled
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - persistent_volumes

  - role: kubernetes-apps/snapshots
    when: inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - snapshots
      - csi-driver

  - role: kubernetes-apps/container_runtimes
    when:
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - container-runtimes

  - role: kubernetes-apps/container_engine_accelerator
    when: nvidia_accelerator_enabled
    tags:
      - container_engine_accelerator

  - role: kubernetes-apps/cloud_controller/oci
    when:
      - cloud_provider is defined
      - cloud_provider == "oci"
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - oci

  - role: kubernetes-apps/metallb
    when:
      - metallb_enabled
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - metallb

  - role: kubernetes-apps/nfs_external_provisioner
    when:
      - nfs_external_provisioner_enabled
    tags:
      - nfs_external_provisioner

  - role: kubernetes-apps/aws_efs_csi_driver
    when:
      - aws_efs_csi_enabled
    tags:
      - aws-efs-csi-driver

  - role: kubernetes-apps/default_storageclass
    when:
      - aws_efs_csi_enabled or nfs_external_provisioner_enabled
    tags:
      - default_storageclass

  - role: kubernetes-apps/ingress_controller/ingress_nginx
    when:
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - ingress_nginx

  - role: kubernetes-apps/cert_manager
    when:
      - cert_manager_enabled
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - cert_manager

  - role: kubernetes-apps/hyperregistry
    when:
      - hyperregistry_enabled
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - hyperregistry

  - role: kubernetes-apps/gateway
    when:
      - gateway_enabled
      - cert_manager_enabled
    tags:
      - gateway

  - role: kubernetes-apps/hyperauth
    when:
      - hyperauth_enabled
    tags:
      - hyperauth

  - role: kubernetes-apps/efk
    when:
      - efk_enabled
    tags:
      - efk

  - role: kubernetes-apps/prometheus
    when:
      - prometheus_enabled
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - prometheus
  - role: kubernetes-apps/grafana
    when:
      - prometheus_enabled
      - hyperauth_enabled
      - grafana_enabled
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - grafana
  - role: kubernetes-apps/service_mesh
    when:
      - service_mesh_enabled
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - service_mesh

  - role: kubernetes-apps/cluster_api
    when:
      - cluster_api_enabled
      - cert_manager_enabled
    tags:
      - cluster_api

  - role: kubernetes-apps/template-service-broker
    when:
      - template_service_broker_enabled
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - template-service-broker

  - role: kubernetes-apps/federation
    when:
      - federation_enabled
    tags:
      - federation

  - role: kubernetes-apps/catalog-controller
    when:
      - catalog_controller_enabled
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - catalog-controller

  - role: kubernetes-apps/hypercloud
    when:
      - hypercloud_enabled
      - cert_manager_enabled
      - hyperauth_enabled
      - cluster_api_enabled
      - federation_enabled
      - template_service_broker_enabled
    tags:
      - hypercloud

  - role: kubernetes-apps/console_provisioner
    when:
      - console_provisioner_enabled
    tags:
      - console_provisioner

  - role: kubernetes-apps/cicd
    when:
      - cicd_enabled
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - cicd

  - role: kubernetes-apps/image_validating_webhook
    when:
      - image_validating_webhook_enabled
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - image_validating_webhook

  - role: kubernetes-apps/ai_devops
    when:
      - ai_devops_enabled
      - cert_manager_enabled
      - service_mesh_enabled
      - console_provisioner_enabled
      - inventory_hostname == groups['kube_control_plane'][0]
    tags:
      - ai_devops

