apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifest/cert-manager
    repoURL: 'https://github.com/tmax-cloud/argocd-installer'
    targetRevision: main
