apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api-provider-aws
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet:
        tlas:
        - name: credentials
          value: Y3JlZGVudGlhbAo=
    path: manifest/cluster-api-provider-aws
    repoURL: https://github.com/tmax-cloud/argocd-installer
    targetRevision: main
