apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-stats
  namespace: monitoring
spec:
  jobLabel: envoy-stats
  namespaceSelector:
    any: true
  selector: {}
  podMetricsEndpoints:
  - path: /stats/prometheus
    relabelings:
    - sourceLabels:
      - __meta_kubernetes_pod_container_port_name
      action: keep
      regex: '.*-envoy-prom'
    - sourceLabels:
      - __address__
      - __meta_kubernetes_pod_annotation_prometheus_io_port
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:15090
      targetLabel: __address__
    - action: labeldrop
      regex: __meta_kubernetes_pod_label_(.+)
    - sourceLabels:
      - __meta_kubernetes_namespace
      action: replace
      targetLabel: namespace
    - sourceLabels:
      - __meta_kubernetes_pod_name
      action: replace
      targetLabel: pod_name
